#!/bin/bash
set -e

# Setup code directory
CodeDir=$HOME/Code
mkdir -p $CodeDir

GoBinary="go1.12.7.linux-amd64.tar.gz"
TmuxBinary="tmux-2.9a.tar.gz"

# Install prepreqs
OS=`uname -a`
echo $OS
if [[ $OS = *"Linux penguin"* ]] ; then
	echo "Found ChromeOS"
	sudo apt install -y git curl zsh

  # Install Go
	if [[ ! -f $GoBinary ]]; then
		curl -O https://dl.google.com/go/$GoBinary
		sudo tar xpvf $GoBinary -C /usr/local
	fi
	PATH=$PATH:/usr/local/go/bin

  # Install Tmux
  sudo apt install -y gcc make libevent-dev libncurses-dev
  if [[ ! -f $TmuxBinary ]]; then
    curl -O -L https://github.com/tmux/tmux/releases/download/2.9a/$TmuxBinary
    tar xpvf $TmuxBinary
    cd tmux-2.9a
    ./configure && make
    sudo make install
    cd ../
    rm -rf tmux-2.9a
  fi

  # Set Shell
  echo "Set Shell to ZSH"
  sudo chsh -s /usr/bin/zsh $USER
fi

# Find the installers and run them iteratively
cd "$(dirname "$0")"/..
git ls-tree --name-only -r HEAD | grep install.sh | while read -r installer; do
	echo "› ${installer}..."
	sh -c "$installer"
done
